# Generated by Django 4.2 on 2023-04-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('cpf', models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False)),
                ('nomeCompleto', models.CharField(max_length=150)),
                ('telefone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('sexo', models.CharField(max_length=1)),
                ('idade', models.DecimalField(decimal_places=0, max_digits=3)),
                ('tipoSanguineo', models.CharField(max_length=3)),
                ('alergias', models.CharField(max_length=500)),
                ('medicacaoDrogas', models.CharField(max_length=500)),
                ('historicoDoencas', models.CharField(max_length=500)),
                ('queixaPrincipal', models.CharField(max_length=500)),
                ('nivelDor', models.DecimalField(decimal_places=0, max_digits=2)),
                ('classificacaoRisco', models.CharField(choices=[('nao-urgente', 'nao-urgente'), ('pouco-urgente', 'pouco-urgente'), ('urgente', 'urgente'), ('emergencia', 'emergencia')], default='pouco-urgente', max_length=20)),
                ('observacoes', models.CharField(max_length=500)),
                ('pressaoSanguinea', models.CharField(max_length=6)),
                ('oxigenacao', models.CharField(max_length=6)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('frequebciaRitmca', models.CharField(max_length=6)),
                ('data', models.CharField(max_length=10)),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=250)),
                ('nomeParamedicoResponsavel', models.CharField(max_length=150)),
                ('documentoTrabalhoParamedico', models.CharField(max_length=10)),
            ],
        ),
    ]
