# Generated by Django 4.2 on 2023-05-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_paciente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='telefone',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='classificacaoRisco',
            new_name='classificacao_risco',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='documentoTrabalhoParamedico',
            new_name='documento_trabalho_paramedico',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='frequebciaRitmca',
            new_name='frequencia_ritmica',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='historicoDoencas',
            new_name='historico_doencas',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='medicacaoDrogas',
            new_name='medicacao_drogas',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='nivelDor',
            new_name='nivel_dor',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='nomeCompleto',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='nomeParamedicoResponsavel',
            new_name='nome_paramedico_responsavel',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='pressaoSanguinea',
            new_name='pressao_sanguinea',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='queixaPrincipal',
            new_name='queixa_principal',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='tipoSanguineo',
            new_name='tipo_sanguineo',
        ),
    ]
