# Generated by Django 4.2.1 on 2023-06-23 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ficha_paciente', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='paramedico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fichas', to=settings.AUTH_USER_MODEL),
        ),
    ]
