# Generated by Django 4.2 on 2023-04-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfissionaldeSaude',
            fields=[
                ('cpf', models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False)),
                ('areaAtuacao', models.CharField(max_length=50)),
                ('nomeCompleto', models.CharField(max_length=150)),
                ('telefone', models.DecimalField(decimal_places=0, max_digits=11)),
                ('documentoTrabalho', models.CharField(max_length=10)),
                ('unidadeDeAtendimento', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
