# Generated by Django 4.2 on 2023-04-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionaldesaude',
            name='areaAtuacao',
        ),
        migrations.AddField(
            model_name='profissionaldesaude',
            name='campo_escolha',
            field=models.CharField(choices=[('CRM', 'Médico(a)'), ('COREN', 'Enfermeiro(a)'), ('DRF', 'Paramédico(a)')], default='CRM', max_length=5),
        ),
    ]
