# Generated by Django 4.2.1 on 2023-05-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionaldesaude',
            name='celular',
            field=models.DecimalField(decimal_places=0, default=5500000000000, max_digits=11),
        ),
    ]
