# Generated by Django 4.2.1 on 2023-05-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionaldesaude',
            name='cpf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
