# Generated by Django 4.2.1 on 2023-05-22 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_paciente', '0001_initial'),
        ('hospital', '0002_alter_profissionaldesaude_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissionaldesaude',
            options={'verbose_name_plural': 'Profissionais de Saúde'},
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='anamnese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='ficha_paciente.anamnese'),
        ),
        migrations.AlterField(
            model_name='fichapaciente',
            name='paramedico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
