# Generated by Django 4.2.1 on 2023-05-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_profissionaldesaude_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionaldesaude',
            name='senha',
        ),
        migrations.AlterField(
            model_name='profissionaldesaude',
            name='celular',
            field=models.CharField(max_length=13),
        ),
    ]
