# Generated by Django 4.2.1 on 2023-05-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_profissionaldesaude_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichapaciente',
            options={'verbose_name_plural': 'Fichas Pacientes'},
        ),
    ]
