# Generated by Django 4.2.1 on 2023-05-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_profissionaldesaude_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionaldesaude',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='profissionaldesaude',
            name='username',
        ),
        migrations.AlterField(
            model_name='profissionaldesaude',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
